function names = lesionFeatureOrder()
%LESIONFEATUREORDER Column order of the per-candidate lesion feature vector.
%   Mirrors lesion_features.py FEATURE_ORDER.

names = { ...
    'b_over_g', 'r_over_g', 'saturation', ...
    'grad_mag_rim', 'edge_sharpness', 'boundary_smoothness', ...
    'area_px', 'perimeter_px', 'circularity', 'eccentricity', 'solidity', ...
    'dist_od_dd', 'dist_fovea_dd', 'dist_vessel_px', ...
    'local_contrast', 'bg_ratio' ...
    };
end
