function m = module2Equivalent()
%MODULE2EQUIVALENT Column-name mapping from Stage 2 (S2-01..S2-45) to the
%   previous Module 2 implementation's rank-comparison equivalent. This is
%   documentation for cross-checking against a different CSV, not consumed
%   downstream. Mirrors features.py MODULE2_EQUIVALENT.

keysList = { ...
    'vessel_density_pct', 'vessel_fragmentation', 'vessel_components', ...
    'vessel_largest_tree_pct', 'vessel_length', 'vessel_orientation_coherence', ...
    'nv_score', 'nv_score_max', ...
    'od_x', 'od_y', 'fovea_x', 'fovea_y', 'od_fovea_dist_dd', ...
    'haem_count', 'haem_q_min', 'haem_q_max', 'rule421_haem', ...
    'hard_exudate_count', 'hard_exudate_area_pct', 'ma_count' ...
    };
valuesList = { ...
    'vessel_pct', 'vessel_frag', 'vessel_comps', ...
    'vessel_largest_pct', 'vessel_skel_len', 'vessel_coh', ...
    'nv_fine', 'nv_fine_max', ...
    'od_x', 'od_y', 'fovea_x', 'fovea_y', 'fovea_od_dd', ...
    'hem_n', 'q_min', 'q_max', 'rule421', ...
    'exu_n', 'exu_area', 'ma_n' ...
    };
m = containers.Map(keysList, valuesList);
end
